# --- Basic configuration
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'

# --- Events
after-login-command = []
after-startup-command = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = "move-mouse window-lazy-center"

# --- Windows configurations
[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top =        10
outer.right =      10

[workspace-to-monitor-force-assignment]
7 = 'secondary'
8 = 'secondary'
9 = 'secondary'
0 = 'secondary'

[mode.main.binding]

# --- Misc mappings
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'
alt-shift-f = 'fullscreen'
alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
ctrl-shift-tab = 'move-node-to-monitor --wrap-around next'
alt-shift-semicolon = 'mode service'

# --- Move focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# --- Move direction
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# --- Resize
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# --- Changing workspaces
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 0'

# --- Moving windows to workspaces
cmd-shift-1 = 'move-node-to-workspace 1'
cmd-shift-2 = 'move-node-to-workspace 2'
cmd-shift-3 = 'move-node-to-workspace 3'
cmd-shift-4 = 'move-node-to-workspace 4'
cmd-shift-5 = 'move-node-to-workspace 5'
cmd-shift-6 = 'move-node-to-workspace 6'
cmd-shift-7 = 'move-node-to-workspace 7'
cmd-shift-8 = 'move-node-to-workspace 8'
cmd-shift-9 = 'move-node-to-workspace 9'
cmd-shift-0 = 'move-node-to-workspace 0'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

# --- Move specific applications to differents workspaces
[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'com.void'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = "move-node-to-workspace 3"

[[on-window-detected]]
if.app-id = 'io.httpie.desktop'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = "com.tinyapp.TablePlus"
run = 'move-node-to-workspace 5'

[[on-window-detected]]
if.app-id = "dev.kdrag0n.MacVirt"
run = "move-node-to-workspace 6"

[[on-window-detected]]
if.app-id = "us.zoom.xos"
run = 'move-node-to-workspace 7'

[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = 'move-node-to-workspace 7'

[[on-window-detected]]
if.app-id = 'com.apple.mail'
run = 'move-node-to-workspace 8'

[[on-window-detected]]
if.app-id = 'com.cron.electron'
run = 'move-node-to-workspace 8'

[[on-window-detected]]
if.app-id = 'notion.id'
run = 'move-node-to-workspace 9'

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace 0'
